name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Check for package.json
      run: if [ ! -f wp-content/themes/twentynineteen/package.json ]; then echo "package.json not found"; exit 1; fi

    - name: Install Dependencies
      run: cd wp-content/themes/twentynineteen && npm install

    - name: Build Styles
      run: cd wp-content/themes/twentynineteen && npm run build

    - name: Watch for Changes (Optional)
      env:
        SHELL: /bin/bash
      run: cd wp-content/themes/twentynineteen && npm run watch

    - name: Run Tests
      run: cd wp-content/themes/twentynineteen && npm test
