name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List directory contents
      run: ls -al

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/app/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Create app directory if it doesn't exist
      run: mkdir -p app

    - name: List app directory contents
      run: ls -al app

    - name: Check for package.json
      run: if [ ! -f wp-content/themes/twentynineteen/package.json ]; then echo "package.json not found"; exit 1; fi
    
    - name: Install Dependencies
      run: cd wp-content/themes/twentynineteen && npm install
    

    - name: Lint code
      run: |
        cd app
        npm run lint

    - name: Run tests
      run: |
        cd app
        npm test

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'DEV-Web-WP'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: Use new random secret
      run: echo "New random secret is ${{ secrets.NEW_RANDOM_SECRET }}"

    - name: Notify on success
      if: success()
      uses: actions/github-script@v6
      with:
        script: |
          const message = "Deployment to DEV-Web-WP successful";
          const to = process.env.NOTIFY_EMAIL;
          // Add your notification logic here, e.g., send an email or post to a Slack channel

    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          const message = "Deployment to DEV-Web-WP failed";
          const to = process.env.NOTIFY_EMAIL;
          // Add your notification logic here, e.g., send an email or post to a Slack channel

    - name: Create job summary
      if: always()
      run: echo "Deployment job completed" >> $GITHUB_STEP_SUMMARY